spring:
  datasource:
    url: jdbc:mysql://localhost:3306/grupo-18-db
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    extras:
      springsecurity5:
        enabled: true
        cache: false